plugins {
    id 'java'
    id 'io.qameta.allure' version '2.11.2'
}

group = 'com.rental'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testImplementation 'io.cucumber:cucumber-java:7.18.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.18.0'

    // hw_17 — REST-assured
    testImplementation 'io.rest-assured:rest-assured:4.4.0'
    implementation 'com.google.code.gson:gson:2.10.1'

    // hw_19 — Selenide
    testImplementation 'com.codeborne:selenide:7.3.3'

    // hw_20 — Allure
    testImplementation 'io.qameta.allure:allure-junit5:2.25.0'
    testImplementation 'io.qameta.allure:allure-rest-assured:2.25.0'
}

allure {
    version = '2.25.0'
    autoconfigure = true

    useJUnit5 {
        version = '2.25.0'
    }
}

test {
    useJUnitPlatform()
}