plugins {
    id 'java'
}

group = 'com.rental'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testImplementation 'io.cucumber:cucumber-java:7.18.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.18.0'

    // hw_17 — REST-assured
    testImplementation 'io.rest-assured:rest-assured:4.4.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}

test {
    useJUnitPlatform()
}